  spring:
    security:
      user:
        name: user
        password: pass
    datasource:
      url: jdbc:hsqldb:hsql://localhost:9003/trainingdb
      username: SA
      password:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  server:
    port: 9000