  spring:
    security:
      user:
        name: user
        password: pass
    datasource:
      url: jdbc:sqlserver://DESKTOP-HSQDKL8:1433;databaseName=springbootdb;trustServerCertificate=true
      username: sa
      password: pass
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  server:
    port: 9000